swagger: '2.0'
info:
  title: Shifter API
  description: Shifter API Version 2 allows you to operate project and Your Wordpress
  version: "2.0"
host: https://kelbes0rsk.execute-api.us-east-1.amazonaws.com/
schemes:
  - https
basePath: /production/v2
produces:
  - application/json
paths:
  /projects:
    get:
      description: You can get the infomation of your projects
      tags:
        - projects
      responses:
        200:
          description: Get your projects infomation
          schema:
            type: array
            items:
              properties:
                project_id:
                  type: string
                project_name:
                  type: string
                project_owner:
                  type: string
                update_time:
                  type: string
                wordpress_site_url:
                  type: string
                access_url:
                  type: string
                domain:
                  type: string
                deploy_type:
                  type: string
                raw_url:
                  type: string
                create_time:
                  type: string
    post:
      description: Create new project
      tags:
        - projects
      parameters:
        - name: request
          in: body
          required: true
          schema:
            properties:
              project_name:
                type: string
      responses:
        201:
          description: Create successfully
          schema:
            properties:
              project_id:
                type: string
              project_name:
                type: string
              shifter_cdn_url:
                type: string
              wordpress_site_url:
                type: string
        400:
          description: It exceeds the maximum number of your projects
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
  /projects/{project_id}:
    delete:
      description: Delete your project
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: project ID
          type: string
      responses:
        204:
          description: Success
        404:
          description: can not find your project
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
        400:
          description: Invaild parameters
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
    get:
      description: Get your project infomation
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: project ID
          type: string
      responses:
        200:
          description: Project status response
          schema:
            properties:
              project_name:
                type: string
              stock_state:
                type: string
              project_id:
                type: string
              wordpress_site_url:
                type: string
              domain:
                type: string
              php_version:
                type: string
              access_url:
                type: string
              update_time:
                type: string
              last_launched:
                type: string
              disk_usage:
                type: string
              deploy_type:
                type: string
              raw_url:
                type: string
              create_time:
                type: string
        404:
          description: can not find your project
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
  /projects/{project_id}/project_name:
    put:
      description: Update your project name
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: project ID
          type: string
        - name: request
          in: body
          required: true
          schema:
            properties:
              project_name:
                type: string
                description: project name
      responses:
        204:
          description: Update successfully
        404:
          description: can not find your project
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
        400:
          description: Invaild parameters
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
  /projects/{project_id}/deployment:
    put:
      description: Update deploy setting of specfied project
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: project ID
          type: string
        - name: request
          in: body
          required: true
          schema:
            properties:
              automation:
                type: boolean
                description: if set to true, deploy automatically after generating Artifact
      responses:
        204:
          description: Update successfully
        404:
          description: can not find your project
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
        400:
          description: Invaild parameters
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
  /projects/{project_id}/wordpress_site/{action}:
    post:
      description: Start WordPress
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: project ID
          type: string
        - name: action
          in: path
          required: true
          description: action name. "start" or "stop"
          type: string
      responses:
        201:
          description: WordPress started or stopped successfully.
        404:
          description: can not find your project
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
        400:
          description: Invaild parameters
          schema:
            "$ref": "#/definitions/CommonErrorResponse"

  /projects/{project_id}/wordpress_site/check_wp_setup/{notification_id}:
    get:
      description: Start WordPress
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: project ID
          type: string
        - name: notification_id
          in: path
          required: true
          description: notification ID
          type: string
      responses:
        200:
          description: WordPress Site importing status
          schema:
            type: string
        400:
          description: Invaild parameters
          schema:
            "$ref": "#/definitions/CommonErrorResponse"
        404:
          description: missing your project(errorCode:missing_project) or notificationId(errorCode:missing_notification_id)
          schema:
            properties:
              message:
                type: string
              errorCode:
                type: string
definitions:
  LoginPostRequest:
    properties:
      username:
        type: string
      password:
        type: string
  LoginPostResponse:
    properties:
      AccessToken:
        type: string
  LoginErrorResponse:
    properties:
      message:
        type: string
        description: Invalid Username or Password
  PlanResponse:
    properties:
      id:
        type: string
      object:
        type: string
      amount:
        type: integer
      created:
        type: string
      currency:
        type: string
      interval:
        type: string
      interval_count:
        type: integer
      livemode:
        type: boolean
      name:
        type: string
      trial_period_days:
        type: integer
      metadata:
        type: object
        properties:
          projects_limit:
            type: string
          domain_setting:
            type: string
          netlify_deploy:
            type: string
          user_limit:
            type: string
          import_archives:
            type: string
          export_archives:
            type: string
          backup:
            type: string
          max_transfer_gb:
            type: string
          max_disk_gb:
            type: string
          enable_subuser:
            type: string
  PlanWithAnResponse:
    properties:
      id:
        type: string
      object:
        type: string
      amount:
        type: integer
      created:
        type: string
      currency:
        type: string
      interval:
        type: string
      interval_count:
        type: integer
      livemode:
        type: boolean
      name:
        type: string
      trial_period_days:
        type: integer
      annualprice:
        type: integer
      metadata:
        type: object
        properties:
          projects_limit:
            type: string
          domain_setting:
            type: string
          netlify_deploy:
            type: string
          user_limit:
            type: string
          import_archives:
            type: string
          export_archives:
            type: string
          backup:
            type: string
          max_transfer_gb:
            type: string
          max_disk_gb:
            type: string
          enable_subuser:
            type: string
  CommonErrorResponse:
    properties:
      message:
        type: string
